version: "2"
services:
  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=666666
      - MYSQL_DATABASE=vertx_blueprint
  mongo:
    image: mongo:3.3
    expose:
      - "27017"
  keycloak-server:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  redis:
    image: redis:latest
    expose:
      - "6379"
  inventory-microservice:
    image: vertx-blueprint/inventory-microservice
    links:
      - redis
    depends_on:
      - redis
    expose:
      - "8086"
  product-microservice:
    image: vertx-blueprint/product-microservice
    links:
      - mysql
    depends_on:
      - mysql
    expose:
      - "8082"
  account-microservice:
    image: vertx-blueprint/account-microservice
    links:
      - mysql
    depends_on:
      - mysql
    expose:
      - "8081"
  store-microservice:
    image: vertx-blueprint/store-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8085"
  cache-infrastructure:
    image: vertx-blueprint/cache-infrastructure
    links:
      - redis
    depends_on:
      - redis
  shopping-cart-microservice:
    image: vertx-blueprint/shopping-cart-microservice
    links:
      - mysql
      - inventory-microservice
      - product-microservice
      - cache-infrastructure
    depends_on:
      - mysql
    expose:
      - "8084"
  order-microservice:
    image: vertx-blueprint/order-microservice
    links:
      - mysql
    depends_on:
      - mysql
      - shopping-cart-microservice
      - inventory-microservice
    expose:
      - "8090"
  monitor-dashboard:
    image: vertx-blueprint/monitor-dashboard
    ports:
      - "9100:9100"
  api-gateway:
    image: vertx-blueprint/api-gateway
    ports:
      - "8787:8787"
    links:
      - keycloak-server
      - inventory-microservice
      - product-microservice
      - shopping-cart-microservice
      - order-microservice
      - account-microservice
      - store-microservice
    extra_hosts:
      - "dockernet:${EXTERNAL_IP}"